name: CI

on:
  push:
    branches: 
    - "main"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install dependencies
      run:  sudo apt install -y bats shellcheck
    - name: Run tests
      run:  make
